### ISSUE TITLE
OLS connection error

### ISSUE THREAD

**Issue by edoud1** [PRIDE-Toolsuite/ols-dialog#12]
Was just attempting to do a little searching for the correct disease term when I got this"OLS connection error"

I am definitely online and haven't had any other firewall issues although it's possible there's something with the University.
![image](https://user-images.githubusercontent.com/62359987/129243481-f197221c-7d6a-42f8-8200-e54286d19292.png)

The worst is that the message won't clear - it immediately pops back up if I click 'ok' or 'x' so I think I'll have to restart the submission unfortunately.

**Comment by selvaebi** [comment]
PLease search with exact id like below,

![Screenshot 2021-08-13 at 15 27 40](https://user-images.githubusercontent.com/33631243/129372582-78a1e704-3e23-4f31-92a4-60f80698f48a.png)
