### ISSUE TITLE
PRIDE OLS Connection E

### ISSUE THREAD

**Issue by collelvd** [PRIDE-Toolsuite/ols-dialog#13]

**Comment by collelvd** [comment]
I am using Xenopus tropicalis for my experiment, which is not listed in the dropdown menu. I am definitely connected to the internet and see no firewall issues on my computer. I am using the most recent version of Java jdx and pride submission tool
<img width="597" alt="Screen Shot 2021-09-28 at 2 41 09 PM" src="https://user-images.githubusercontent.com/91564576/135146614-add59a6e-a4db-45f6-b1f9-a33df18f1046.png">
.

**Comment by ypriverol** [comment]
This problem has been solved.

**Comment by ypriverol** [comment]
New version of submission tool https://github.com/PRIDE-Archive/px-submission-tool/releases/download/2.5.5/px-submission-tool-2.5.5.zip
