### ISSUE TITLE
Where to set the proxy when using Pride submission tool?

### ISSUE THREAD

**Issue by jgn301** [PRIDE-Toolsuite/ols-dialog#17]
In the Pride submission tool `config.props` file, I successfully set the details of my proxy server. However, when I want to enter a specific mass spec device during the Pride submission procedure, the OLS window opens and an error message appears: `Failed to contact the OLS [...]`. 

Does the OLS take over the proxy settings from the Pride submission tool? If not, where do I need to enter the proxy settings? 
Do I need to use `java -Dhttp.proxyHost=my.proxy.domain.com -Dhttp.proxyPort=3128 -jar ols-dialog.jar` and the Pride submission tool would be "your project"? I'm not sure I understand the terminology what "your project" would be in this case. 
Is it possible to change the proxy settings without having to restart the submission procedure?

Kind regards
jgn

**Comment by selvaebi** [comment]
Hi @jgn301  , i will go the through the OLS  proxy issue.,The latest command you have posted might be due to wrong proxy host or port , ```java -Dhttp.proxyHost=localhost -Dhttp.proxyPort=8080 -jar px-submission-tool-2.6.0.ja``` worked for me perfectly

**Comment by jgn301** [comment]
This is what above command produces on my machine 🤔
```
PS D:\Downloads\px-submission-tool-2.6.0\lib> java -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8080 -jar ols-dialog-3.4.20-SNAPSHOT.jar
Error: Could not find or load main class .proxyHost=localhost
PS D:\Downloads\px-submission-tool-2.6.0\lib> cd ..
PS D:\Downloads\px-submission-tool-2.6.0> java -Dhttps.proxyHost=localhost -Dhttps.proxyPort=8080 -jar px-submission-tool-2.6.0.jar
Error: Could not find or load main class .proxyHost=localhost
```
The workaround that I used now is to just not use the OLS dialog, instead just select one of the suggested entries in Step 8 of Px submission (_additional details_), then _export summary file_ as .px file in the _submission summary_ step, look up the appropriate OLS entries on the web and correct the lines
```
MTD	species	[NEWT, xxxxx, species name from OLS=title of the respective OLS entry, ]
MTD	tissue	[BTO, BTO:xxxxxxx, tissue name from OLS, ]
MTD	instrument	[MS, MS:xxxxxxx, device name from OLS, ]
```
in the .px file. Then restart submission in _bulk submission_ mode and select the altered .px file. Then the correct values should already be filled in in step 8. 
Kind regards

**Comment by my-randa** [comment]
I already corrected the lines in the .px file. But I can't find  _bulk submission mode_ ,is it _Complete Submission_?However, my search results could only be submitted by Partial Submission which leads to only _export_ the .px file. Where can I select the altered .px file?
Any help would be appreciated.

**Comment by selvaebi** [comment]
@my-randa you can use Revalidation option

**Comment by my-randa** [comment]
@selvaebi THANK YOU SO MUCH! It worked out！
